### PR TITLE
bugfix: Change qualityNames key to qualities to match API response

### PR DESCRIPTION
**Pull request by thomas-mcdonald**
Just hit this error on master in GameItemSchema

```
		"status": 1,
		"items_game_url": "http://media.steampowered.com/apps/440/scripts/items/items_game.9c3a78207db4c80958e51e32626e1518d397adb2.txt",
		"qualities": {
			"Normal": 0,
			"rarity1": 1,
			"rarity2": 2,
			"vintage": 3,
			"rarity3": 4,
			"rarity4": 5,
			"Unique": 6,
			"community": 7,
			...
		},
		"originNames": [
			...
```

### CODE REVIEW

**Comment by koraktor** [comment]
What exact error are you experiencing?
Looking at the code, it will already use the static quality keys as name if no name is found in `qualityNames`.

**Comment by thomas-mcdonald** [comment]
Is there a game where "qualityNames" exists?

The current code throws a NoMethodError for the TF2 response (440) because `data[:qualityNames]` is nil.

**Comment by koraktor** [comment]
`qualityNames` is still there for me.

**Comment by koraktor** [comment]
@thomas-mcdonald Is this still an issue for you? I can’t reproduce your problem.

**Pull request closed without merging**
