### PR TITLE
Adding ability to pull summary data

### PR DESCRIPTION
**Pull request by bfosberry**
Fetch summary will pull data from the summary subsection
and store game name, id and game server id when present.

### CODE REVIEW

**Comment by bfosberry** [comment]
Ping on this PR, I've updated this to support the JSON api, also have a few bug fixes

**Comment by bfosberry** [comment]
Unsure why Im getting extra content in here, must have been a bad rebase, I'll squash this down and separate out bug fixes

**Comment by koraktor** [comment]
I finally merged this, but took the freedom to rename the methods as they’re about the game server information and not the player summary as a whole. The latter will replace the old XML code sometime in the future.

Thank you (for the patch and your patience).

**Comment by bfosberry** [comment]
Perfect! I'll update code my end to use the new names, thanks!!

**Pull request merged**
