### PR TITLE
Adding nil guard in steam_group

### PR DESCRIPTION
**Pull request by bfosberry**

### CODE REVIEW

**Comment by koraktor** [comment]
Have you an example group without an avatar? I guess this was handled differently in the past on Steam’s end, e.g. using a default URL.

**Comment by bfosberry** [comment]
There may still be a default URL, but if the fetch fails no value is set. If other attributes are checked they return nil but avatar returns an exception because we're not nil checking

**Comment by koraktor** [comment]
Finally found the time to merge this. Thank you.

**Comment by bfosberry** [comment]
Thanks!

**Pull request merged**
